services:
  backend:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - mock-api-net
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  database:
    image: mongo
    networks:
      - mock-api-net
    volumes:
      - mongo-data:./db

networks:
  mock-api-net:
    driver: bridge

volumes:
  mongo-data:
