services:
  backend:
    build:
      context: .
    container_name: mock-api
    ports:
      - 3000:3000
    networks:
      - mock-api-net
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  database:
    image: mongo
    container_name: mongo
    networks:
      - mock-api-net
    volumes:
      - ./db:/data/db

networks:
  mock-api-net:
    driver: bridge
