services:
  backend-dev:
    build:
      context: .
    image: mock-api:dev
    container_name: mock-api-dev
    env_file:
      - ./.env
    ports:
      - 3000:$PORT
    networks:
      - mock-api-net
    volumes:
      - .:/usr/src/app
    depends_on:
      - database-dev
  database-dev:
    image: mongo
    container_name: mongodb-dev
    networks:
      - mock-api-net
    volumes:
      - ./db:/data/db

networks:
  mock-api-net:
    driver: bridge
